/**
 * @file lvgl_hw_config.h
 *
 */

#ifndef LV_HW_CONFIG_H
#define LV_HW_CONFIG_H

#define CONFIG_LV_MEM_SIZE 48U
#define CONFIG_LVGL_PREDEFINED_DISPLAY_NONE 1

#define CONFIG_LVGL_TFT_DISPLAY_CONTROLLER_GC9A01A
#define CONFIG_LVGL_TFT_DISPLAY_PROTOCOL_SPI
#define CONFIG_LVGL_TFT_DISPLAY_SPI_HSPI 1
#define CONFIG_LVGL_DISPLAY_USE_SPI_CS
#define CONFIG_LVGL_DISP_SPI_MOSI 13
#define CONFIG_LVGL_DISP_SPI_CLK 14
#define CONFIG_LVGL_DISP_SPI_CS 15
#define CONFIG_LVGL_DISP_PIN_DC 2
#define CONFIG_LVGL_DISP_PIN_RST 33

#define CONFIG_LVGL_DISPLAY_ORIENTATION_LANDSCAPE  
//#define CONFIG_LVGL_DISPLAY_ORIENTATION_LANDSCAPE_INVERTED  
//#define CONFIG_LVGL_DISPLAY_ORIENTATION_PORTRAIT 
//#define CONFIG_LVGL_DISPLAY_ORIENTATION_PORTRAIT_INVERTED   
#define CONFIG_LVGL_DISPLAY_WIDTH 240
#define CONFIG_LVGL_DISPLAY_HEIGHT 240
#define CONFIG_LVGL_DISPLAY_ORIENTATION 2 //TODO

//TODO
#define CONFIG_LVGL_TOUCH_X_MIN 0  
#define CONFIG_LVGL_TOUCH_Y_MIN 0  
#define CONFIG_LVGL_TOUCH_X_MAX 0 
#define CONFIG_LVGL_TOUCH_Y_MAX 0  
#define CONFIG_LVGL_TOUCH_I2C_SDA 21  
#define CONFIG_LVGL_TOUCH_I2C_SCL 22  
#define CONFIG_LVGL_TOUCH_SPI_CS 5  
#define CONFIG_LVGL_TOUCH_PIN_IRQ 25
//

//TODO SINCE THIS IS SHOULD NOT BE UNDER HW
#define CONFIG_LV_FONT_MONTSERRAT_10    1
#define CONFIG_LV_FONT_MONTSERRAT_12    1
#define CONFIG_LV_FONT_MONTSERRAT_14    1
#define CONFIG_LV_FONT_MONTSERRAT_16    1
#define CONFIG_LV_FONT_MONTSERRAT_18    0
#define CONFIG_LV_FONT_MONTSERRAT_20    0
#define CONFIG_LV_FONT_MONTSERRAT_22    1
#define CONFIG_LV_FONT_MONTSERRAT_24    0
#define CONFIG_LV_FONT_MONTSERRAT_26    0
#define CONFIG_LV_FONT_MONTSERRAT_28    1
#define CONFIG_LV_FONT_MONTSERRAT_30    0
#define CONFIG_LV_FONT_MONTSERRAT_32    1
#define CONFIG_LV_FONT_MONTSERRAT_34    0
#define CONFIG_LV_FONT_MONTSERRAT_36    0
#define CONFIG_LV_FONT_MONTSERRAT_38    0
#define CONFIG_LV_FONT_MONTSERRAT_40    0
#define CONFIG_LV_FONT_MONTSERRAT_42    0
#define CONFIG_LV_FONT_MONTSERRAT_44    0
#define CONFIG_LV_FONT_MONTSERRAT_46    0
#define CONFIG_LV_FONT_MONTSERRAT_48    0
/*--END OF LV_HW_CONFIG_H--*/

#endif /*LV_HW_CONFIG_H*/